<a href="https://colab.research.google.com/github/jyothika5968/Python_For_DA/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([[1,2,3]],dtype=float)
print(a)

[[1. 2. 3.]]


In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
c=np.array([1,2,3])
print(c)

[1 2 3]


In [ ]:
len(b)

3

In [ ]:
d=np.array([1,2,3,4,5,6])
len(d)

6

In [ ]:
e=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(e)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
type(e)

numpy.ndarray

In [ ]:
np.ndim(e)

3

In [ ]:
e.ndim

3

In [ ]:
f= np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(f)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [ ]:
f.ndim

4

In [ ]:
# Get the Shape of an numpy Shape
a.shape

(1, 3)

In [ ]:
b.shape

(3, 3)

In [ ]:
c.shape

(3,)

In [ ]:
d.shape

(6,)

In [ ]:
e.shape

(1, 3, 3)

In [ ]:
#ACCESSING / CHANGING SPECIFIC ELEMENTS,ROWS AND COLUMNS
z=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
z[0,6]=40
print(z)

[[ 1  2  3  4  5  6 40]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#ZEROS & ONES METHOD IN NUMPY
np.zeros((3,3),dtype='str')

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [ ]:
varb=30

In [ ]:
np.full((3,3),varb,dtype='int')

array([[30, 30, 30],
       [30, 30, 30],
       [30, 30, 30]])

In [ ]:
np.random.rand((5,5),dtype=int)

TypeError: rand() got an unexpected keyword argument 'dtype'

In [ ]:
np.random.rand(5,5)

array([[0.76528811, 0.25234237, 0.7053725 , 0.18848505, 0.20323136],
       [0.44042066, 0.06851075, 0.90651352, 0.68965244, 0.99714288],
       [0.86007386, 0.02612694, 0.94691972, 0.4495177 , 0.97237703],
       [0.77655709, 0.41423808, 0.8004095 , 0.94902112, 0.63698206],
       [0.07889968, 0.85291208, 0.06026927, 0.12831839, 0.87876825]])

In [ ]:
np.random.randint(10,100,size=(5,5))

array([[84, 98, 59, 48, 85],
       [78, 51, 93, 27, 13],
       [24, 63, 66, 93, 52],
       [29, 31, 11, 51, 66],
       [17, 85, 59, 92, 78]])

In [ ]:
np.identity((5),dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
# extract all the first 3 rows of the last 5 th column in a given numpy 2d array 'a'


In [ ]:
ab=np.array([[84, 98, 59, 48, 85,57],
             [78, 51, 93, 27, 13,46],
             [24, 63, 66, 93, 52,36],
             [29, 31, 11, 51, 66,38],
             [17, 85, 59, 92, 78,27]])


In [ ]:
type(ab)

numpy.ndarray

In [ ]:
ab[:3,-5:]

array([[98, 59, 48, 85, 57],
       [51, 93, 27, 13, 46],
       [63, 66, 93, 52, 36]])

In [ ]:
#given a positive no ngreater than 2 create a numpy array of size (n*n) with all zeros and ones such tht it forms a shape of PLUS

import numpy as np
def create_shape_of_array(n):
  arrayy=np.zeros((n,n),dtype=int)
  mid = n // 2
  arrayy[:,mid]=1
  arrayy[mid,:]=1

  return arrayy
n=7
result=create_shape_of_array(n)
print(result)


[[0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]


In [ ]:
# Arithmetic operations -maths & stats
np.identity((7),dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [ ]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a+3

array([4, 5, 6, 7, 8])

In [ ]:
a-2

array([-1,  0,  1,  2,  3])

In [ ]:
a*5

array([ 5, 10, 15, 20, 25])

In [ ]:
a/6

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333])

In [ ]:
a//4

array([0, 0, 0, 1, 1])

In [ ]:
a.max()

np.int64(5)

In [ ]:
a.min()

np.int64(1)

In [ ]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
b.ndim

2

In [ ]:
b.max()

np.int64(10)

In [ ]:
b.min()

np.int64(1)